package org.firstinspires.ftc.teamcode.subsystems.path.state.enums;

public enum bigAndSmall2Enum {
    INTAKE_START,
    START_SHOOT,
    OUTTAKE_PRELOAD,
    SHOOT_TOPSTART,
    TOPSTART_TOPEND,
    TOPEND_TOPSTART,
    TOPSTART_SHOOT,
    OUTTAKE_TOP,
    SHOOT_MIDDLESTART,
    MIDDLESTART_MIDDLEEND,
    MIDDLEEND_MIDDLESTART,
    MIDDLESTART_SHOOT,
    OUTTAKE_MIDDLE,
    SHOOT_BOTTOMSTART,
    BOTTOMSTART_BOTTOMEND,
    BOTTOMEND_BOTTOMSTART,
    BOTTOMSTART_SHOOT,
    OUTTAKE_BOTTOM,
    SHOOT_END
}