package org.firstinspires.ftc.teamcode.subsystems.path.state.enums;

public enum smallEnum {
    START_PRELOAD,
    OUTTAKE_PRELOAD,
    PRELOAD_BOTTOMSTART,
    BOTTOMSTART_BOTTOMEND,
    INTAKESTART_BOTTOM,
    BOTTOMEND_BOTTOMSTART,
    INTAKEEND_BOTTOM,
    BOTTOMSTART_SHOOT,
    OUTTAKE_BOTTOM,
    SHOOT_MIDDLESTART,
    MIDDLESTART_MIDDLEEND,
    INTAKESTART_MIDDLE,
    MIDDLEEND_MIDDLESTART,
    INTAKEEND_MIDDLE,
    MIDDLESTART_SHOOT,
    OUTTAKE_MIDDLE,
    SHOOT_TOPSTART,
    TOPSTART_TOPEND,
    INTAKESTART_TOP,
    TOPEND_TOPSTART,
    INTAKEEND_TOP,
    TOPSTART_SHOOT,
    OUTTAKE_TOP,
    SHOOT_END
}